language: python

branches:
  only:
    - master

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - python setup.py flake8
  - python setup.py nosetests

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)